steps:
# Step 1: Build the Docker Image and push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - | 
      #!/bin/bash
      echo "$${key_p8}" > key.p8
      echo "$${firebase_adminsdk_json}" > firebase-adminsdk.json
      cp .env.sample .env
      docker build -t us-central1-docker.pkg.dev/push-dev-apps/ar-d-services-base-usce1/push-delivery-node-image:$SHORT_SHA .
      docker push us-central1-docker.pkg.dev/push-dev-apps/ar-d-services-base-usce1/push-delivery-node-image:$SHORT_SHA
  secretEnv: ['key_p8','firebase_adminsdk_json']

# Step 2: Create the Cloud Deploy Pipeline and release
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - | 
      #!/bin/bash
      gcloud container clusters get-credentials gke-d-services-base-usce1 --region us-central1 --project push-dev-apps
      export DEP_EXIST=$(kubectl get deployment -n apps | grep push-delivery-node)
      if [[ -z "$${DEP_EXIST// /}" ]]
      then
        echo "Creating Deployment..."
        gcloud artifacts docker tags add us-central1-docker.pkg.dev/push-dev-apps/ar-d-services-base-usce1/push-delivery-node-image:$SHORT_SHA us-central1-docker.pkg.dev/push-dev-apps/ar-d-services-base-usce1/push-delivery-node-image:init
        kubectl apply -f ./dev-pipeline/k8s/deployment.yaml
        echo "Created Deployment."
      else
        echo "Updating Deployment..."
        sed -i 's|image: "us-central1-docker.pkg.dev/push-dev-apps/ar-d-services-base-usce1/push-delivery-node-image:init"|image: "us-central1-docker.pkg.dev/push-dev-apps/ar-d-services-base-usce1/push-delivery-node-image:$SHORT_SHA"|g' ./dev-pipeline/k8s/deployment.yaml
        kubectl apply -f ./dev-pipeline/k8s/deployment.yaml -n apps
        echo "Updated Deployment..."
      fi
availableSecrets:
  secretManager:
  - versionName: projects/push-dev-apps/secrets/key_p8/versions/1
    env: 'key_p8'
  - versionName: projects/push-dev-apps/secrets/firebase_adminsdk_json/versions/1
    env: 'firebase_adminsdk_json'
options:
 logging: CLOUD_LOGGING_ONLY
 workerPool: 'projects/push-dev-apps/locations/us-central1/workerPools/worker-pool-d-services-base-usce1'
